{"name": "test_invalid_credentials[edge]", "status": "broken", "statusDetails": {"message": "AttributeError: 'LoginPage' object has no attribute 'click'. Did you mean: 'clic'?", "trace": "self = <tests.test_login.TestLogin object at 0x00000228B8463FB0>\n\n    def test_invalid_credentials(self):\n        login_page = LoginPage(self.driver)\n>       login_page.log_into_application(\"Invalid Email\", \"Invalid Password\")\n\ntests\\test_login.py:17: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages\\login_page.py:30: in log_into_application\n    self.click_login_button()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.login_page.LoginPage object at 0x00000228B8D09A00>\n\n    def click_login_button(self):\n>     self.click(self.login_button)\nE     AttributeError: 'LoginPage' object has no attribute 'click'. Did you mean: 'clic'?\n\npages\\login_page.py:24: AttributeError"}, "attachments": [{"name": "stdout", "source": "3aa2fedb-c817-4eec-acd2-d29ee8661139-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "initialize_driver", "value": "'edge'"}], "start": 1710442393499, "stop": 1710442393829, "uuid": "38545fe0-600f-41ad-8078-75069748d033", "historyId": "a990e0960df6e74856be76c66f8e2554", "testCaseId": "ef7373e7d568430ffce9b3d52770a421", "fullName": "tests.test_login.TestLogin#test_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('initialize_driver')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-U9R56RQR"}, {"name": "thread", "value": "15700-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}