{"uuid": "d3f377b3-fc37-413d-a7e8-cc36170da600", "children": ["99c5ac1b-713b-4967-9b92-4be5eca13640"], "befores": [{"name": "setup_teardown", "status": "passed", "start": 1710442259504, "stop": 1710442260733}], "afters": [{"name": "setup_teardown::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"partial link text\",\"selector\":\"Logout\"}\n  (Session info: chrome=122.0.6261.128); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF78A78AD02+56930]\n\t(No symbol) [0x00007FF78A6FF602]\n\t(No symbol) [0x00007FF78A5B42E5]\n\t(No symbol) [0x00007FF78A5F98ED]\n\t(No symbol) [0x00007FF78A5F9A2C]\n\t(No symbol) [0x00007FF78A63A967]\n\t(No symbol) [0x00007FF78A61BCDF]\n\t(No symbol) [0x00007FF78A6381E2]\n\t(No symbol) [0x00007FF78A61BA43]\n\t(No symbol) [0x00007FF78A5ED438]\n\t(No symbol) [0x00007FF78A5EE4D1]\n\tGetHandleVerifier [0x00007FF78AB06F8D+3711213]\n\tGetHandleVerifier [0x00007FF78AB604CD+4077101]\n\tGetHandleVerifier [0x00007FF78AB5865F+4044735]\n\tGetHandleVerifier [0x00007FF78A829736+706710]\n\t(No symbol) [0x00007FF78A70B8DF]\n\t(No symbol) [0x00007FF78A706AC4]\n\t(No symbol) [0x00007FF78A706C1C]\n\t(No symbol) [0x00007FF78A6F68D4]\n\tBaseThreadInitThunk [0x00007FF8EEAE257D+29]\n\tRtlUserThreadStart [0x00007FF8F010AA58+40]\n\n", "trace": "  File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\atipj\\Documents\\Portfolio\\Lambdatest\\Selenium_Python_101\\DemoPytest\\test_fixtures_1.py\", line 22, in setup_teardown\n    driver.find_element(By.PARTIAL_LINK_TEXT,\n  File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1710442262246, "stop": 1710442262291}], "start": 1710442259504, "stop": 1710442262291}