{"name": "test_square_number", "status": "skipped", "statusDetails": {"message": "XFAIL Result Add Numbers & Not Multiply Numbers\n\nAssertionError: assert 20 == (10 ** 2)", "trace": "self = <DemoPytest.test_fail.Test_Math object at 0x00000228B8400050>\n\n    @pytest.mark.xfail(reason=\"Result Add Numbers & Not Multiply Numbers\")\n    def test_square_number(self):\n      num = 10\n      result = num + num # 10 * 10 = 100\n>     assert result == num ** 2\nE     assert 20 == (10 ** 2)\n\nDemoPytest\\test_fail.py:14: AssertionError"}, "start": 1710442254976, "stop": 1710442254976, "uuid": "094874d8-187f-45d9-a6ee-33cc08ced2e3", "historyId": "23a23b8622fa3789fbbc4d7ae70cc82a", "testCaseId": "23a23b8622fa3789fbbc4d7ae70cc82a", "fullName": "DemoPytest.test_fail.Test_Math#test_square_number", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(reason='Result Add Numbers & Not Multiply Numbers')"}, {"name": "parentSuite", "value": "DemoPytest"}, {"name": "suite", "value": "test_fail"}, {"name": "subSuite", "value": "Test_Math"}, {"name": "host", "value": "LAPTOP-U9R56RQR"}, {"name": "thread", "value": "15700-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "DemoPytest.test_fail"}]}