{"name": "test_invalid_credentials[firefox]", "status": "broken", "statusDetails": {"message": "AttributeError: 'LoginPage' object has no attribute 'click'. Did you mean: 'clic'?", "trace": "self = <tests.test_login.TestLogin object at 0x00000228B8463DA0>\n\n    def test_invalid_credentials(self):\n        login_page = LoginPage(self.driver)\n>       login_page.log_into_application(\"Invalid Email\", \"Invalid Password\")\n\ntests\\test_login.py:17: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages\\login_page.py:30: in log_into_application\n    self.click_login_button()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.login_page.LoginPage object at 0x00000228B8BFE5D0>\n\n    def click_login_button(self):\n>     self.click(self.login_button)\nE     AttributeError: 'LoginPage' object has no attribute 'click'. Did you mean: 'clic'?\n\npages\\login_page.py:24: AttributeError"}, "attachments": [{"name": "stdout", "source": "92c5dbf0-2f96-49d9-9577-1e454d149fc5-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "initialize_driver", "value": "'firefox'"}], "start": 1710442386812, "stop": 1710442386896, "uuid": "d6821098-6ccb-4763-b9f0-193f2a325788", "historyId": "c60d5fa1bb90eb693d90c799e2a9b574", "testCaseId": "ef7373e7d568430ffce9b3d52770a421", "fullName": "tests.test_login.TestLogin#test_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('initialize_driver')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-U9R56RQR"}, {"name": "thread", "value": "15700-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}